version: '3.8'

services:
  gptr-mcp:
    build: .
    ports:
      - "8111:8111"
    environment:
      - MCP_TRANSPORT=streamable-http
      - DOCKER_CONTAINER=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8111/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
